README.md
exporters/powerdns/build.sh
exporters/powerdns/exporter.yml
scripts/fetch_synthesis_definition.sh

There were a couple of problems that are fixed with this PR:
- The exporter-powerdns binary wasn't created.
- The definitions were failing when checking out the established commit.

Fix issue in exporter-powerdns

---

exporters/powerdns/exporter.yml

Upgrade version of PowerDNS integration because the 0.0.1 was already created and the prerelease pipeline failed

upgrade powerdns version

---

Makefile

When running in Linux I had an issue with sh.

fix(makefile): calling bash script with bash

---

.github/workflows/prerelease.yml

Pipeline go version 1.16

---

exporters/powerdns/exporter.yml

PowerDNS 0.0.3

---

exporters/powerdns/exporter.yml

PowerDNS 0.0.5

---

exporters/powerdns/exporter.yml
exporters/powerdns/win_build.ps1

Remove PowerDNS entity definitions and bump version

---

exporters/powerdns/exporter.yml
scripts/s3-publish-schema.yml

chore(release): new powerdns release to support new distributions

---

exporters/ibmmq/exporter.yml

chore(release): new ibmmq release to support new distributions

---

exporters/ibmmq/exporter.yml
exporters/ibmmq/ibmmq-config.yml.sample

Fix https://github.com/newrelic/newrelic-prometheus-exporters-packages/issues/108
Fix some security vulnerabilities
On the downsize a release has not been created yet this is a commit from master, I checked the history and most of the changes are simply security updates, therefore I wonder if you should wait or pull the trigger.

[IBMmq] bump version

---

exporters/mongodb/build.sh
exporters/mongodb/e2e/e2e_spec.yml
exporters/mongodb/exporter.yml
exporters/mongodb/mongodb-config.yml.sample
exporters/mongodb/mongodb.json.tmpl
exporters/mongodb/mongodb.prometheus.json.tmpl

PR to add mongodb build scripts and templates

add mongodb package (NR-52106)

---

.github/workflows/release.yml

Fix Test Package Installation action on release.

Fix version to check when checking correct package creation on release

---

.github/workflows/manual-artifacts-generation.yml
exporters/ibmmq/e2e/e2e_spec.yml
exporters/ibmmq/exporter.yml

Tested locally and triggered the package creation with:
- https://github.com/newrelic/newrelic-prometheus-exporters-packages/actions/runs/3847523880/jobs/6554158341
-

feat(ibmmq): windows release

---

exporters/mongodb/build-exporter-windows.sh
exporters/mongodb/e2e/e2e_spec.yml
exporters/mongodb/exporter.yml

Create mongodb windows release and arm

feat(mongodb): windows release and arm [NR-75937]

---

exporters/mongodb3/mongodb3-config.yml.sample

fix to change the sample file to the new nri-mongodb3 naming

fix mongodb config sample

---

exporters/mongodb3/e2e/e2e_spec.yml
exporters/mongodb3/exporter.yml
exporters/mongodb3/mongodb3.json.tmpl

Fix an error when escaping of collection and index filters

Correct escaping of collection and index filters and add to e2e

---

exporters/aerospike/aerospike-config.yml.sample
exporters/aerospike/aerospike.json.tmpl

Ticket: https://issues.newrelic.com/browse/NEWRELIC-7605
Git Issue: https://github.com/newrelic/newrelic-prometheus-exporters-packages/issues/174
Updated the exporter file path from the configuration file.

passing exporter file path aerospike

---

.github/workflows/e2e.yml

Add goreleaser install step

---

exporters/mongodb3/build-exporter-linux.sh
exporters/mongodb3/e2e/e2e_spec.yml
exporters/mongodb3/exporter.yml

Just updating the exporter digest and bumping the version

Mongodb 1.0.0 release

---

exporters/ibmmq/build-exporter-windows.sh
exporters/ibmmq/e2e/agent_dir/newrelic-infra-agent/Dockerfile
exporters/ibmmq/exporter.yml

Release new version of the integration with a bump of the exporter and the fix #236

release ibmmq
